version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  pg_data:
